[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "../backend/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  command = "npm run serve --prefix frontend"
  port = 8888
  targetPort = 8080