[build]
  base = "."
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "backend/functions"

[functions]
  directory = "backend/functions" 

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  command = "npm run dev --prefix frontend"
  port = 8888
  targetPort = 5173